name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        working-directory: bin
        run: |
          yarn

      - name: run build
        working-directory: bin
        run: |
          yarn build

      - name: upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bin/data
          publish_branch: build
          force_orphan: true
          
      - name: Run a one-line script
        env:
          accessKeyId: "${{ secrets.OSS_ACCESS_KEY_ID }}"
          accessKeySecret: "${{ secrets.OSS_ACCESS_KEY_SECRET }}"
        run: |
          bash ./sync.sh "$accessKeyId" "$accessKeySecret"
